// Both independent passes use the same meanings, without sharing proposed kinds.
export const knowledgeSourceInstructions = `Source structure and scope:
- Read the complete heading hierarchy. A heading supplies context, not necessarily the actor. Section labels such as Skills, Experience and Projects classify the facts below them; they are not people or organizations.
- In a named person's resume/profile, a career entry under Experience with a company, job title and dates explicitly describes that person's employment. Skill lists describe the named person's stated skills. Resolve the omitted subject from the supplied ancestor headings; never substitute the employer or a job title for the person performing the work.
- A personal project entry supports the person's contribution to that project, not necessarily sole authorship or legal ownership. In project descriptions, a technology stack states what the project uses; in a person's Skills section it states has_skill. Client lists, desired jobs, sample resumes, negations and quotations do not establish employment or proficiency.
- Structured lists and tables can establish explicit facts without a full sentence. Employers, stated skills, project dependencies and awards are useful document facts even when the entry is short. Do not reject these as incidental bare names. Unrelated navigation links, social sharing buttons and passing mentions may be incidental.
- Use precise predicates: works_for connects a person to an employer, has_skill to a stated skill, contributed_to to a personal project, received to an award/designation. A software product uses its implementation languages, libraries and tools; runs_on is only for its execution/hosting environment (such as an operating system), not its implementation language or interface technique. Holding a job title is not works_for that title; a repository link is not ownership of its hosting company. In warn/off mode vocabulary suggestions are not a closed list. Preserve dates and qualifiers in evidence.
- Summaries must describe only the entity's role or facts stated in this source. Do not add encyclopedic definitions, unstated capabilities, assumed industry facts or biographical details. A short source-grounded summary or null is preferable to a plausible unsupported definition.
- An alternative proper name is different from a descriptive expansion. Do not add a name followed by a generic classification (for example 'Rust programming language') as an alias of that name. Such expansions are generic references, not alternative proper names.

Shared entity kind definitions (apply independently to source meaning):
- An explicit source classification takes precedence over these defaults (for example, 'Redis 기술' identifies a technology in that source). A generic section label such as 'technology stack' is not an explicit kind assignment to each item. Never replace the source's referent with outside knowledge about a similarly named company or product.
- person: an explicitly named individual. A job title, pronoun or anonymous author is not a named person.
- organization: a named company, institution or organized group, when the source refers to that organization.
- product: a named software application, tool, database engine, operating system or tangible product. Use product for executable tools even when listed in a technology stack.
- service: a named hosted service, cloud offering, SaaS or API offering. Distinguish a service from the organization providing it; a brand can refer to either, so use the source's referent.
- technology: a programming language, protocol, standard, technique or software framework/library, rather than a named application or hosted service. A list label 'technology stack' does not turn every item into kind technology.
- project: a named bounded undertaking. A section headed Personal Projects can still describe a product; classify the named thing described, not the section label.
- One referent has one entity entry. Do not duplicate a named software tool as both a project and a product merely because it appears under Personal Projects. Distinct entries with the same name require source evidence that they are actually different referents.
- recognition: a named award, honor or designation, including a named community recognition program; certification: a named qualification or credential.
- role: a defined role discussed as a topic. A job title used only to refer to the resume's author is a generic reference, not another entity.
- location: a named place; event: an explicitly named occurrence; document: a named publication or work; concept: a reusable named idea that does not fit a more specific kind.
- Do not use these kinds as a whitelist when the organization allows custom kinds, and never force a source into an inaccurate kind. A sentence or assertion is not a concept or event merely because it is true.`;
