-- Generated by pnpm db:generate. Do not edit.
CREATE EXTENSION IF NOT EXISTS vector;
CREATE TYPE "public"."document_status" AS ENUM('pending', 'processing', 'ready', 'failed', 'archived');
CREATE TYPE "public"."knowledge_ontology_mode" AS ENUM('off', 'warn', 'strict');
CREATE TYPE "public"."organization_member_status" AS ENUM('active', 'pending', 'blocked', 'removed');
CREATE TYPE "public"."organization_role" AS ENUM('member', 'admin', 'owner');
CREATE TYPE "public"."team_role" AS ENUM('member', 'manager');
CREATE TYPE "public"."knowledge_candidate_status" AS ENUM('pending', 'accepted', 'rejected');
CREATE TYPE "public"."memory_kind" AS ENUM('rule', 'experience', 'decision', 'preference', 'fact');
CREATE TYPE "public"."memory_permission" AS ENUM('read', 'write', 'manage');
CREATE TYPE "public"."memory_principal_kind" AS ENUM('team', 'user');
CREATE TYPE "public"."memory_scope_kind" AS ENUM('organization', 'team', 'user');
CREATE TYPE "public"."memory_source_type" AS ENUM('agent', 'user', 'document', 'system');
CREATE TYPE "public"."memory_status" AS ENUM('active', 'archived');
CREATE TABLE "auth_accounts" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"user_id" uuid NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"issuer" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" text,
	"password" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "auth_sessions" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"user_id" uuid NOT NULL,
	"token" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "auth_verifications" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "ai_request_buckets" (
	"organization_id" uuid NOT NULL,
	"principal_key" text NOT NULL,
	"window_started_at" timestamp with time zone NOT NULL,
	"request_count" integer NOT NULL,
	CONSTRAINT "ai_request_buckets_organization_id_principal_key_window_started_at_pk" PRIMARY KEY("organization_id","principal_key","window_started_at"),
	CONSTRAINT "ai_request_buckets_positive_count_check" CHECK ("ai_request_buckets"."request_count" > 0)
);
CREATE TABLE "document_chunks" (
	"organization_id" uuid NOT NULL,
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"document_id" uuid NOT NULL,
	"ordinal" integer NOT NULL,
	"content" text NOT NULL,
	"search" "tsvector" GENERATED ALWAYS AS (to_tsvector('simple', coalesce(content, ''))) STORED NOT NULL,
	"embedding" vector,
	"embedding_model" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "document_chunks_nonnegative_ordinal_check" CHECK ("document_chunks"."ordinal" >= 0),
	CONSTRAINT "document_chunks_embedding_pair_check" CHECK (("document_chunks"."embedding" IS NULL) = ("document_chunks"."embedding_model" IS NULL))
);
CREATE TABLE "document_scope_changes" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"document_id" uuid NOT NULL,
	"previous_scope" jsonb NOT NULL,
	"scope" jsonb NOT NULL,
	"knowledge" jsonb NOT NULL,
	"changed_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "documents" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"scope_kind" "memory_scope_kind" NOT NULL,
	"team_id" uuid,
	"user_id" uuid,
	"title" text NOT NULL,
	"source_uri" text,
	"object_key" text NOT NULL,
	"checksum" text NOT NULL,
	"mime_type" text NOT NULL,
	"size_bytes" integer DEFAULT 0 NOT NULL,
	"status" "document_status" DEFAULT 'pending' NOT NULL,
	"error_message" text,
	"processing_attempts" integer DEFAULT 0 NOT NULL,
	"processing_lease_id" uuid,
	"processing_started_at" timestamp with time zone,
	"processed_at" timestamp with time zone,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "documents_scope_owner_check" CHECK (("documents"."scope_kind" = 'organization' AND "documents"."team_id" IS NULL AND "documents"."user_id" IS NULL)
        OR ("documents"."scope_kind" = 'team' AND "documents"."team_id" IS NOT NULL AND "documents"."user_id" IS NULL)
        OR ("documents"."scope_kind" = 'user' AND "documents"."team_id" IS NULL AND "documents"."user_id" IS NOT NULL)),
	CONSTRAINT "documents_nonnegative_size_check" CHECK ("documents"."size_bytes" >= 0),
	CONSTRAINT "documents_nonnegative_attempts_check" CHECK ("documents"."processing_attempts" >= 0)
);
CREATE TABLE "organization_agent_tokens" (
	"organization_id" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"token_hash" text NOT NULL,
	"token" text,
	"masked" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "organization_members" (
	"organization_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"role" "organization_role" DEFAULT 'member' NOT NULL,
	"status" "organization_member_status" DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "organization_members_organization_id_user_id_pk" PRIMARY KEY("organization_id","user_id")
);
CREATE TABLE "organizations" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"default_team_id" uuid,
	"ontology_mode" "knowledge_ontology_mode" DEFAULT 'warn' NOT NULL,
	"ontology" jsonb DEFAULT '{"nodeKinds":["person","organization","product","service","project","technology","location","recognition","certification","role","event","document","concept"],"edgePredicates":["depends_on","uses","owns","part_of","member_of","works_for","located_in","integrates_with","produces","manages"]}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "team_members" (
	"organization_id" uuid NOT NULL,
	"team_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"role" "team_role" DEFAULT 'member' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "team_members_team_id_user_id_pk" PRIMARY KEY("team_id","user_id")
);
CREATE TABLE "teams" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"name" text NOT NULL,
	"image" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "ingestion_receipts" (
	"organization_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"operation" text NOT NULL,
	"key" text NOT NULL,
	"payload_hash" text NOT NULL,
	"resource_id" uuid NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "ingestion_receipts_organization_id_user_id_operation_key_pk" PRIMARY KEY("organization_id","user_id","operation","key"),
	CONSTRAINT "ingestion_receipts_key_length" CHECK (length("ingestion_receipts"."key") between 1 and 256),
	CONSTRAINT "ingestion_receipts_hash_shape" CHECK ("ingestion_receipts"."payload_hash" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "ingestion_receipts_operation" CHECK ("ingestion_receipts"."operation" in ('memory.create', 'document.upload', 'document.retry'))
);
CREATE TABLE "knowledge_candidate_edges" (
	"organization_id" uuid NOT NULL,
	"candidate_id" uuid NOT NULL,
	"edge_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "knowledge_candidate_edges_pk" PRIMARY KEY("organization_id","candidate_id","edge_id")
);
CREATE TABLE "knowledge_candidate_nodes" (
	"organization_id" uuid NOT NULL,
	"candidate_id" uuid NOT NULL,
	"node_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "knowledge_candidate_nodes_pk" PRIMARY KEY("organization_id","candidate_id","node_id")
);
CREATE TABLE "knowledge_candidates" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"document_id" uuid NOT NULL,
	"chunk_id" uuid NOT NULL,
	"model" text NOT NULL,
	"graph" jsonb NOT NULL,
	"item_reviews" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"assessment" jsonb,
	"status" "knowledge_candidate_status" DEFAULT 'pending' NOT NULL,
	"reviewed_by" uuid,
	"review_reason" text,
	"reviewed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "knowledge_candidates_organization_id_id_unique" UNIQUE("organization_id","id"),
	CONSTRAINT "knowledge_candidates_review_state_check" CHECK (("knowledge_candidates"."status" = 'pending' AND "knowledge_candidates"."reviewed_by" IS NULL AND "knowledge_candidates"."reviewed_at" IS NULL)
        OR ("knowledge_candidates"."status" IN ('accepted', 'rejected') AND "knowledge_candidates"."reviewed_by" IS NOT NULL AND "knowledge_candidates"."reviewed_at" IS NOT NULL))
);
CREATE TABLE "knowledge_edge_sources" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"edge_id" uuid NOT NULL,
	"memory_id" uuid,
	"chunk_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "knowledge_edge_sources_identity_unique" UNIQUE NULLS NOT DISTINCT("organization_id","edge_id","memory_id","chunk_id"),
	CONSTRAINT "knowledge_edge_sources_exactly_one_source_check" CHECK (("knowledge_edge_sources"."memory_id" IS NOT NULL) <> ("knowledge_edge_sources"."chunk_id" IS NOT NULL))
);
CREATE TABLE "knowledge_edges" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"scope_kind" "memory_scope_kind" DEFAULT 'organization' NOT NULL,
	"team_id" uuid,
	"user_id" uuid,
	"source_node_id" uuid NOT NULL,
	"target_node_id" uuid NOT NULL,
	"predicate" text NOT NULL,
	"properties" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "knowledge_edges_identity_unique" UNIQUE NULLS NOT DISTINCT("organization_id","scope_kind","team_id","user_id","source_node_id","predicate","target_node_id"),
	CONSTRAINT "knowledge_edges_scope_owner_check" CHECK (("knowledge_edges"."scope_kind" = 'organization' AND "knowledge_edges"."team_id" IS NULL AND "knowledge_edges"."user_id" IS NULL)
        OR ("knowledge_edges"."scope_kind" = 'team' AND "knowledge_edges"."team_id" IS NOT NULL AND "knowledge_edges"."user_id" IS NULL)
        OR ("knowledge_edges"."scope_kind" = 'user' AND "knowledge_edges"."team_id" IS NULL AND "knowledge_edges"."user_id" IS NOT NULL)),
	CONSTRAINT "knowledge_edges_non_self_check" CHECK ("knowledge_edges"."source_node_id" <> "knowledge_edges"."target_node_id")
);
CREATE TABLE "knowledge_node_merges" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"source_node_id" uuid NOT NULL,
	"target_node_id" uuid NOT NULL,
	"source_kind" text NOT NULL,
	"source_canonical_name" text NOT NULL,
	"merged_by" uuid NOT NULL,
	"reason" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "knowledge_node_sources" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"node_id" uuid NOT NULL,
	"memory_id" uuid,
	"chunk_id" uuid,
	"description" text,
	"names" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "knowledge_node_sources_identity_unique" UNIQUE NULLS NOT DISTINCT("organization_id","node_id","memory_id","chunk_id"),
	CONSTRAINT "knowledge_node_sources_exactly_one_source_check" CHECK (("knowledge_node_sources"."memory_id" IS NOT NULL) <> ("knowledge_node_sources"."chunk_id" IS NOT NULL)),
	CONSTRAINT "knowledge_node_sources_names_object_check" CHECK (jsonb_typeof("knowledge_node_sources"."names") = 'object')
);
CREATE TABLE "knowledge_nodes" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"scope_kind" "memory_scope_kind" DEFAULT 'organization' NOT NULL,
	"team_id" uuid,
	"user_id" uuid,
	"kind" text NOT NULL,
	"canonical_name" text NOT NULL,
	"canonical_name_key" text GENERATED ALWAYS AS (lower(regexp_replace(trim(canonical_name), '[[:space:]]+', ' ', 'g'))) STORED,
	"summary" text,
	"search" "tsvector" GENERATED ALWAYS AS (to_tsvector('simple', coalesce(canonical_name, '') || ' ' || coalesce(summary, ''))) STORED NOT NULL,
	"embedding" vector,
	"embedding_model" text,
	"properties" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "knowledge_nodes_identity_unique" UNIQUE NULLS NOT DISTINCT("organization_id","scope_kind","team_id","user_id","kind","canonical_name"),
	CONSTRAINT "knowledge_nodes_scope_owner_check" CHECK (("knowledge_nodes"."scope_kind" = 'organization' AND "knowledge_nodes"."team_id" IS NULL AND "knowledge_nodes"."user_id" IS NULL)
        OR ("knowledge_nodes"."scope_kind" = 'team' AND "knowledge_nodes"."team_id" IS NOT NULL AND "knowledge_nodes"."user_id" IS NULL)
        OR ("knowledge_nodes"."scope_kind" = 'user' AND "knowledge_nodes"."team_id" IS NULL AND "knowledge_nodes"."user_id" IS NOT NULL)),
	CONSTRAINT "knowledge_nodes_embedding_pair_check" CHECK (("knowledge_nodes"."embedding" IS NULL) = ("knowledge_nodes"."embedding_model" IS NULL))
);
CREATE TABLE "knowledge_graph_versions" (
	"organization_id" uuid PRIMARY KEY NOT NULL,
	"revision" uuid DEFAULT uuidv7() NOT NULL
);
CREATE TABLE "memories" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"scope_kind" "memory_scope_kind" NOT NULL,
	"team_id" uuid,
	"user_id" uuid,
	"kind" "memory_kind" NOT NULL,
	"title" text NOT NULL,
	"content" text NOT NULL,
	"search" "tsvector" GENERATED ALWAYS AS (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, ''))) STORED NOT NULL,
	"source_type" "memory_source_type" NOT NULL,
	"source_uri" text,
	"source_agent_id" text,
	"source_metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"embedding" vector,
	"embedding_model" text,
	"created_by" uuid NOT NULL,
	"valid_from" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone,
	"status" "memory_status" DEFAULT 'active' NOT NULL,
	"current_version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "memories_scope_owner_check" CHECK (("memories"."scope_kind" = 'organization' AND "memories"."team_id" IS NULL AND "memories"."user_id" IS NULL)
        OR ("memories"."scope_kind" = 'team' AND "memories"."team_id" IS NOT NULL AND "memories"."user_id" IS NULL)
        OR ("memories"."scope_kind" = 'user' AND "memories"."team_id" IS NULL AND "memories"."user_id" IS NOT NULL)),
	CONSTRAINT "memories_expiry_check" CHECK ("memories"."expires_at" IS NULL OR "memories"."expires_at" > "memories"."valid_from"),
	CONSTRAINT "memories_embedding_pair_check" CHECK (("memories"."embedding" IS NULL) = ("memories"."embedding_model" IS NULL))
);
CREATE TABLE "memory_access_grants" (
	"organization_id" uuid NOT NULL,
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"memory_id" uuid NOT NULL,
	"principal_kind" "memory_principal_kind" NOT NULL,
	"team_id" uuid,
	"user_id" uuid,
	"permission" "memory_permission" NOT NULL,
	"granted_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "memory_access_grants_principal_check" CHECK (("memory_access_grants"."principal_kind" = 'team' AND "memory_access_grants"."team_id" IS NOT NULL AND "memory_access_grants"."user_id" IS NULL)
        OR ("memory_access_grants"."principal_kind" = 'user' AND "memory_access_grants"."team_id" IS NULL AND "memory_access_grants"."user_id" IS NOT NULL))
);
CREATE TABLE "memory_versions" (
	"organization_id" uuid NOT NULL,
	"memory_id" uuid NOT NULL,
	"version" integer NOT NULL,
	"title" text NOT NULL,
	"content" text NOT NULL,
	"source_type" "memory_source_type" NOT NULL,
	"source_uri" text,
	"source_agent_id" text,
	"source_metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"embedding" vector,
	"embedding_model" text,
	"access_grants" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"valid_from" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone,
	"status" "memory_status" NOT NULL,
	"changed_by" uuid NOT NULL,
	"change_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "memory_versions_memory_id_version_pk" PRIMARY KEY("memory_id","version"),
	CONSTRAINT "memory_versions_positive_version_check" CHECK ("memory_versions"."version" > 0),
	CONSTRAINT "memory_versions_expiry_check" CHECK ("memory_versions"."expires_at" IS NULL OR "memory_versions"."expires_at" > "memory_versions"."valid_from"),
	CONSTRAINT "memory_versions_embedding_pair_check" CHECK (("memory_versions"."embedding" IS NULL) = ("memory_versions"."embedding_model" IS NULL))
);
CREATE TABLE "app_settings" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"overrides" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "app_settings_singleton_check" CHECK ("app_settings"."id" = 1)
);
CREATE INDEX "auth_accounts_user_id_idx" ON "auth_accounts" USING btree ("user_id");
CREATE UNIQUE INDEX "auth_accounts_issuer_account_id_unique" ON "auth_accounts" USING btree ("issuer","account_id");
CREATE UNIQUE INDEX "auth_sessions_token_unique" ON "auth_sessions" USING btree ("token");
CREATE INDEX "auth_sessions_user_id_idx" ON "auth_sessions" USING btree ("user_id");
CREATE INDEX "auth_verifications_identifier_idx" ON "auth_verifications" USING btree ("identifier");
CREATE INDEX "ai_request_buckets_window_idx" ON "ai_request_buckets" USING btree ("window_started_at");
CREATE UNIQUE INDEX "document_chunks_organization_id_id_unique" ON "document_chunks" USING btree ("organization_id","id");
CREATE UNIQUE INDEX "document_chunks_organization_document_id_unique" ON "document_chunks" USING btree ("organization_id","document_id","id");
CREATE UNIQUE INDEX "document_chunks_document_ordinal_unique" ON "document_chunks" USING btree ("document_id","ordinal");
CREATE INDEX "document_chunks_search_idx" ON "document_chunks" USING gin ("search");
CREATE INDEX "document_scope_changes_document_idx" ON "document_scope_changes" USING btree ("organization_id","document_id","created_at");
CREATE UNIQUE INDEX "documents_organization_id_id_unique" ON "documents" USING btree ("organization_id","id");
CREATE INDEX "documents_organization_checksum_idx" ON "documents" USING btree ("organization_id","checksum");
CREATE INDEX "documents_scope_idx" ON "documents" USING btree ("organization_id","scope_kind","team_id","user_id");
CREATE UNIQUE INDEX "organization_agent_tokens_hash_unique" ON "organization_agent_tokens" USING btree ("token_hash");
CREATE INDEX "organization_members_user_idx" ON "organization_members" USING btree ("user_id");
CREATE UNIQUE INDEX "organizations_slug_unique" ON "organizations" USING btree ("slug");
CREATE INDEX "team_members_user_idx" ON "team_members" USING btree ("organization_id","user_id");
CREATE UNIQUE INDEX "teams_organization_slug_unique" ON "teams" USING btree ("organization_id","slug");
CREATE UNIQUE INDEX "teams_organization_id_id_unique" ON "teams" USING btree ("organization_id","id");
CREATE UNIQUE INDEX "users_email_unique" ON "users" USING btree ("email");
CREATE INDEX "knowledge_candidate_edges_edge_idx" ON "knowledge_candidate_edges" USING btree ("organization_id","edge_id");
CREATE INDEX "knowledge_candidate_nodes_node_idx" ON "knowledge_candidate_nodes" USING btree ("organization_id","node_id");
CREATE UNIQUE INDEX "knowledge_candidates_organization_chunk_unique" ON "knowledge_candidates" USING btree ("organization_id","chunk_id");
CREATE INDEX "knowledge_candidates_review_queue_idx" ON "knowledge_candidates" USING btree ("organization_id","status","created_at");
CREATE INDEX "knowledge_edge_sources_edge_idx" ON "knowledge_edge_sources" USING btree ("organization_id","edge_id");
CREATE INDEX "knowledge_edge_sources_memory_idx" ON "knowledge_edge_sources" USING btree ("memory_id");
CREATE INDEX "knowledge_edge_sources_chunk_idx" ON "knowledge_edge_sources" USING btree ("chunk_id");
CREATE UNIQUE INDEX "knowledge_edges_organization_id_id_unique" ON "knowledge_edges" USING btree ("organization_id","id");
CREATE INDEX "knowledge_edges_target_idx" ON "knowledge_edges" USING btree ("organization_id","target_node_id");
CREATE INDEX "knowledge_node_merges_source_idx" ON "knowledge_node_merges" USING btree ("organization_id","source_node_id");
CREATE INDEX "knowledge_node_merges_target_idx" ON "knowledge_node_merges" USING btree ("organization_id","target_node_id");
CREATE INDEX "knowledge_node_sources_node_idx" ON "knowledge_node_sources" USING btree ("organization_id","node_id");
CREATE INDEX "knowledge_node_sources_memory_idx" ON "knowledge_node_sources" USING btree ("memory_id");
CREATE INDEX "knowledge_node_sources_chunk_idx" ON "knowledge_node_sources" USING btree ("chunk_id");
CREATE INDEX "knowledge_node_sources_names_idx" ON "knowledge_node_sources" USING gin ("names");
CREATE UNIQUE INDEX "knowledge_nodes_organization_id_id_unique" ON "knowledge_nodes" USING btree ("organization_id","id");
CREATE INDEX "knowledge_nodes_normalized_identity_idx" ON "knowledge_nodes" USING btree ("organization_id","scope_kind","team_id","user_id","kind","canonical_name_key");
CREATE INDEX "knowledge_nodes_search_idx" ON "knowledge_nodes" USING gin ("search");
CREATE UNIQUE INDEX "memories_organization_id_id_unique" ON "memories" USING btree ("organization_id","id");
CREATE INDEX "memories_scope_idx" ON "memories" USING btree ("organization_id","scope_kind","team_id","user_id");
CREATE INDEX "memories_search_idx" ON "memories" USING gin ("search");
CREATE INDEX "memories_validity_idx" ON "memories" USING btree ("organization_id","status","valid_from","expires_at");
CREATE UNIQUE INDEX "memory_access_grants_team_unique" ON "memory_access_grants" USING btree ("memory_id","team_id") WHERE "memory_access_grants"."team_id" IS NOT NULL;
CREATE UNIQUE INDEX "memory_access_grants_user_unique" ON "memory_access_grants" USING btree ("memory_id","user_id") WHERE "memory_access_grants"."user_id" IS NOT NULL;
ALTER TABLE "auth_accounts" ADD CONSTRAINT "auth_accounts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "auth_sessions" ADD CONSTRAINT "auth_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "ai_request_buckets" ADD CONSTRAINT "ai_request_buckets_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "document_chunks" ADD CONSTRAINT "document_chunks_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "document_chunks" ADD CONSTRAINT "document_chunks_organization_document_fk" FOREIGN KEY ("organization_id","document_id") REFERENCES "public"."documents"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "document_scope_changes" ADD CONSTRAINT "document_scope_changes_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "document_scope_changes" ADD CONSTRAINT "document_scope_changes_changed_by_users_id_fk" FOREIGN KEY ("changed_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "document_scope_changes" ADD CONSTRAINT "document_scope_changes_document_fk" FOREIGN KEY ("organization_id","document_id") REFERENCES "public"."documents"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "documents" ADD CONSTRAINT "documents_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "documents" ADD CONSTRAINT "documents_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "documents" ADD CONSTRAINT "documents_organization_team_fk" FOREIGN KEY ("organization_id","team_id") REFERENCES "public"."teams"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "documents" ADD CONSTRAINT "documents_organization_user_fk" FOREIGN KEY ("organization_id","user_id") REFERENCES "public"."organization_members"("organization_id","user_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "organization_agent_tokens" ADD CONSTRAINT "organization_agent_tokens_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "organization_agent_tokens" ADD CONSTRAINT "organization_agent_tokens_member_fk" FOREIGN KEY ("organization_id","user_id") REFERENCES "public"."organization_members"("organization_id","user_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "organization_members" ADD CONSTRAINT "organization_members_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "organization_members" ADD CONSTRAINT "organization_members_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_default_team_fk" FOREIGN KEY ("id","default_team_id") REFERENCES "public"."teams"("organization_id","id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_organization_team_fk" FOREIGN KEY ("organization_id","team_id") REFERENCES "public"."teams"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_organization_user_fk" FOREIGN KEY ("organization_id","user_id") REFERENCES "public"."organization_members"("organization_id","user_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "teams" ADD CONSTRAINT "teams_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "ingestion_receipts" ADD CONSTRAINT "ingestion_receipts_member_fk" FOREIGN KEY ("organization_id","user_id") REFERENCES "public"."organization_members"("organization_id","user_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_candidate_edges" ADD CONSTRAINT "knowledge_candidate_edges_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_candidate_edges" ADD CONSTRAINT "knowledge_candidate_edges_organization_candidate_fk" FOREIGN KEY ("organization_id","candidate_id") REFERENCES "public"."knowledge_candidates"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_candidate_edges" ADD CONSTRAINT "knowledge_candidate_edges_organization_edge_fk" FOREIGN KEY ("organization_id","edge_id") REFERENCES "public"."knowledge_edges"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_candidate_nodes" ADD CONSTRAINT "knowledge_candidate_nodes_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_candidate_nodes" ADD CONSTRAINT "knowledge_candidate_nodes_organization_candidate_fk" FOREIGN KEY ("organization_id","candidate_id") REFERENCES "public"."knowledge_candidates"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_candidate_nodes" ADD CONSTRAINT "knowledge_candidate_nodes_organization_node_fk" FOREIGN KEY ("organization_id","node_id") REFERENCES "public"."knowledge_nodes"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_candidates" ADD CONSTRAINT "knowledge_candidates_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_candidates" ADD CONSTRAINT "knowledge_candidates_reviewed_by_users_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "knowledge_candidates" ADD CONSTRAINT "knowledge_candidates_organization_document_fk" FOREIGN KEY ("organization_id","document_id") REFERENCES "public"."documents"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_candidates" ADD CONSTRAINT "knowledge_candidates_document_chunk_fk" FOREIGN KEY ("organization_id","document_id","chunk_id") REFERENCES "public"."document_chunks"("organization_id","document_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_edge_sources" ADD CONSTRAINT "knowledge_edge_sources_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_edge_sources" ADD CONSTRAINT "knowledge_edge_sources_organization_edge_fk" FOREIGN KEY ("organization_id","edge_id") REFERENCES "public"."knowledge_edges"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_edge_sources" ADD CONSTRAINT "knowledge_edge_sources_organization_memory_fk" FOREIGN KEY ("organization_id","memory_id") REFERENCES "public"."memories"("organization_id","id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "knowledge_edge_sources" ADD CONSTRAINT "knowledge_edge_sources_organization_chunk_fk" FOREIGN KEY ("organization_id","chunk_id") REFERENCES "public"."document_chunks"("organization_id","id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "knowledge_edges" ADD CONSTRAINT "knowledge_edges_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_edges" ADD CONSTRAINT "knowledge_edges_organization_team_fk" FOREIGN KEY ("organization_id","team_id") REFERENCES "public"."teams"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_edges" ADD CONSTRAINT "knowledge_edges_organization_user_fk" FOREIGN KEY ("organization_id","user_id") REFERENCES "public"."organization_members"("organization_id","user_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_edges" ADD CONSTRAINT "knowledge_edges_organization_source_node_fk" FOREIGN KEY ("organization_id","source_node_id") REFERENCES "public"."knowledge_nodes"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_edges" ADD CONSTRAINT "knowledge_edges_organization_target_node_fk" FOREIGN KEY ("organization_id","target_node_id") REFERENCES "public"."knowledge_nodes"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_node_merges" ADD CONSTRAINT "knowledge_node_merges_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_node_merges" ADD CONSTRAINT "knowledge_node_merges_merged_by_users_id_fk" FOREIGN KEY ("merged_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "knowledge_node_sources" ADD CONSTRAINT "knowledge_node_sources_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_node_sources" ADD CONSTRAINT "knowledge_node_sources_organization_node_fk" FOREIGN KEY ("organization_id","node_id") REFERENCES "public"."knowledge_nodes"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_node_sources" ADD CONSTRAINT "knowledge_node_sources_organization_memory_fk" FOREIGN KEY ("organization_id","memory_id") REFERENCES "public"."memories"("organization_id","id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "knowledge_node_sources" ADD CONSTRAINT "knowledge_node_sources_organization_chunk_fk" FOREIGN KEY ("organization_id","chunk_id") REFERENCES "public"."document_chunks"("organization_id","id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "knowledge_nodes" ADD CONSTRAINT "knowledge_nodes_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_nodes" ADD CONSTRAINT "knowledge_nodes_organization_team_fk" FOREIGN KEY ("organization_id","team_id") REFERENCES "public"."teams"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_nodes" ADD CONSTRAINT "knowledge_nodes_organization_user_fk" FOREIGN KEY ("organization_id","user_id") REFERENCES "public"."organization_members"("organization_id","user_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "knowledge_graph_versions" ADD CONSTRAINT "knowledge_graph_versions_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "memories" ADD CONSTRAINT "memories_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "memories" ADD CONSTRAINT "memories_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "memories" ADD CONSTRAINT "memories_organization_team_fk" FOREIGN KEY ("organization_id","team_id") REFERENCES "public"."teams"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "memories" ADD CONSTRAINT "memories_organization_user_fk" FOREIGN KEY ("organization_id","user_id") REFERENCES "public"."organization_members"("organization_id","user_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "memory_access_grants" ADD CONSTRAINT "memory_access_grants_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "memory_access_grants" ADD CONSTRAINT "memory_access_grants_granted_by_users_id_fk" FOREIGN KEY ("granted_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "memory_access_grants" ADD CONSTRAINT "memory_access_grants_organization_memory_fk" FOREIGN KEY ("organization_id","memory_id") REFERENCES "public"."memories"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "memory_access_grants" ADD CONSTRAINT "memory_access_grants_organization_team_fk" FOREIGN KEY ("organization_id","team_id") REFERENCES "public"."teams"("organization_id","id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "memory_access_grants" ADD CONSTRAINT "memory_access_grants_organization_user_fk" FOREIGN KEY ("organization_id","user_id") REFERENCES "public"."organization_members"("organization_id","user_id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "memory_versions" ADD CONSTRAINT "memory_versions_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "memory_versions" ADD CONSTRAINT "memory_versions_changed_by_users_id_fk" FOREIGN KEY ("changed_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "memory_versions" ADD CONSTRAINT "memory_versions_organization_memory_fk" FOREIGN KEY ("organization_id","memory_id") REFERENCES "public"."memories"("organization_id","id") ON DELETE cascade ON UPDATE no action;
