import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

// Generate from an empty snapshot each time. No upgrade history is retained.
const temporary = mkdtempSync(path.join(tmpdir(), "agent-memory-schema-"));
try {
  execFileSync("./node_modules/.bin/drizzle-kit", ["generate", "--dialect", "postgresql",
    "--schema", "./src/infrastructure/database/schema/index.ts", "--casing", "snake_case",
    "--out", temporary, "--name", "schema"], { encoding: "utf8" });
  const files = readdirSync(temporary).filter((file) => file.endsWith(".sql"));
  if (files.length !== 1) { throw new Error("Expected exactly one current schema SQL file."); }
  const statements = readFileSync(path.join(temporary, files[0]), "utf8").split("--> statement-breakpoint").map((statement) => statement.trim()).filter(Boolean);
  // Referenced composite keys may be unique indexes. Create them before FKs.
  const isForeignKey = (statement) => /^ALTER TABLE[\s\S]*FOREIGN KEY/.test(statement);
  const exported = [...statements.filter((statement) => !isForeignKey(statement)), ...statements.filter(isForeignKey)].join("\n");
  const schema = `-- Generated by pnpm db:generate. Do not edit.\nCREATE EXTENSION IF NOT EXISTS vector;\n${exported.trim()}\n`;
  if (process.argv.includes("--check")) {
    if (readFileSync("database/schema.sql", "utf8") !== schema) {
      throw new Error("database/schema.sql is stale. Run pnpm db:generate.");
    }
  } else {
    writeFileSync("database/schema.sql", schema);
  }
} finally {
  rmSync(temporary, { recursive: true, force: true });
}
